- hosts: all
  become: yes
  tasks:
    - name: gather facts on images
      openstack.cloud.image_info:
      delegate_to: localhost
      become: no
      ignore_errors: yes

    - name: show openstack images
      debug:
        var: openstack_image
      when: openstack_image is defined