- hosts: all
  become: yes
  vars:
    openstack_release_name: yoga
    openstack_rhel_version: 17
  tasks:
    - name: load os variables
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - 'rhel{{ ansible_distribution_major_version }}.yml'
            - rhel9.yml
          paths:
            - 'vars'
      when: ansible_distribution == 'RedHat'

    - name: enable RDO release
      dnf:
        name: https://www.rdoproject.org/repos/rdo-release.el{{ ansible_distribution_major_version }}.rpm
        disable_gpg_check: yes
        state: present
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int in [8,9]
        - openstack_rhel_version >= 17

    - block:
        - name: disable firewall
          service:
            name: firewalld
            state: stopped
            enabled: no

        - include_role:
            name: "{{ role_name }}"
          loop_control:
            loop_var: role_name
          loop:
            - oatakan.rhn
            - ansible-role-rhosp-packstack
            - post-install

      always:
        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister
          when:
            - rhn_debug is not defined or not rhn_debug | bool