- hosts: localhost
  become: no
  vars:
    provider: vmware
    provider_role: "{{ provider }}"
    config_name: "{{ provider }}"
  vars_files:
    - node-config/nodes-{{ config_name }}.yml
  pre_tasks:
    - name: get amis on ec2
      include_role:
        name: ec2-find-amis
      when: provider == 'ec2'
  roles:
    - ansible-role-{{ provider_role | default(provider) }}