- src: https://github.com/oatakan/ansible-role-ec2
  version: origin/master

- src: https://github.com/oatakan/ansible-role-vmware
  version: origin/master

- src: https://github.com/oatakan/ansible-role-ovirt
  version: origin/master

- src: https://github.com/oatakan/ansible-role-kubevirt.git
  version: origin/master

- src: https://github.com/oatakan/ansible-role-rhosp-packstack
  version: origin/master

- src: https://github.com/oatakan/ansible-role-rhn.git
  version: origin/master
  name: oatakan.rhn