---
nfs_share: ''
image_location: "/mnt/images"

os_images:
  - name: Windows Server 2012 r2 v2
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-2012-r2-v2-cloud-kvm.qcow2.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: Windows Server 2016
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-2016-cloud-kvm.qcow2.gz
    properties:
      cpu_arch: x64_64
      os_type: windows

