---

config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

nfs_share: ''
image_location: "/mnt/images"

reboot_after_install: yes

os_images:
  - name: Windows Server 2012 r2 updated
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-2012-r2-cloud-kvm-updated.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: Windows Server 2016 updated
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-2016-standard-core-cloud-kvm.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: Windows 10
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-10-cloud-kvm-base.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: Windows 10 updated
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-10-cloud-kvm-updated.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: CentOS 7 1808
    container_format: bare
    disk_format: qcow2
    state: present
    filename: CentOS-7-x86_64-GenericCloud-1808.qcow2
    properties:
      cpu_arch: x64_64
      os_type: linux
  - name: RHEL 7.5
    container_format: bare
    disk_format: qcow2
    state: present
    filename: rhel-server-7.5-update-3-x86_64-kvm.qcow2
    properties:
      cpu_arch: x64_64
      os_type: linux

