---

config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

nfs_share: ''
image_location: "/mnt/images"

reboot_after_install: no

os_images:
#  - name: Windows Server 2012 r2 updated
#    container_format: bare
#    disk_format: qcow2
#    state: present
#    filename: windows-2012-r2-cloud-kvm-updated.gz
#    properties:
#      cpu_arch: x64_64
#      os_type: windows
  - name: windows-2016-standard-core
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-2016-standard-core-cloud-kvm.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: windows-2019-standard-core
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-2019-standard-core-cloud-kvm.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: windows-10-1809
    container_format: bare
    disk_format: qcow2
    state: present
    filename: windows-10-1809-cloud-kvm.gz
    properties:
      cpu_arch: x64_64
      os_type: windows
  - name: centos76-x64-cloud-1901
    container_format: bare
    disk_format: qcow2
    state: present
    filename: CentOS-7-x86_64-GenericCloud-1901.qcow2
    properties:
      cpu_arch: x64_64
      os_type: linux
  - name: rhel76-x64
    container_format: bare
    disk_format: qcow2
    state: present
    filename: rhel-server-7.6-x86_64-kvm.qcow2
    properties:
      cpu_arch: x64_64
      os_type: linux
  - name: rhel80-x64
    container_format: bare
    disk_format: qcow2
    state: present
    filename: rhel-8.0-x86_64-kvm.qcow2
    properties:
      cpu_arch: x64_64
      os_type: linux

