---
- name: install python-pip package
  yum:
    name: python-pip
    state: present

- name: install the required pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - openstacksdk

- name: add a new key pair
  os_keypair:
    auth:
      auth_url: "{{ clouds.devstack.auth.auth_url }}"
      username: "{{ clouds.devstack.auth.username }}"
      password: "{{ clouds.devstack.auth.password }}"
      project_name: "{{ clouds.devstack.auth.project_name }}"
    name: "abc"
    public_key: "abc"
    state: present

- name: mount share if applicable
  mount:
    path: /mnt
    src: "{{ nfs_share }}"
    fstype: nfs
    opts: nolock
    state: mounted
  when: nfs_share

- include: upload_image.yml os_image='{{ include_item }}'
  with_items: '{{ os_images }}'
  loop_control:
    loop_var: include_item

- name: unmount share if applicable
  mount:
    path: /mnt
    src: "{{ nfs_share }}"
    fstype: nfs
    opts: nolock
    state: absent
  when: nfs_share